### ISSUE TITLE
Trained model

### ISSUE THREAD

**Issue by sidrahhanif** [sleep3r/Diffusion-Handwriting-Generation.pytorch#1]
Hi,

Thanks for implementing the diffusion model for handwriting generation in Pytorch.
I want to ask you about the trained model for the code.
I trained the model from scratch but was not able to replicate the results.

**Comment by sleep3r** [comment]
Hi @sidrahhanif,

Sorry to hear you're facing issues. I'm currently unable to replicate the original results too. I invite you to fork the project and contribute any changes that may help. I will continue refining this implementation and will provide updates when available.

**Comment by sidrahhanif** [comment]
Thanks. I would be happy to contribute to it.
